# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jose Simoes
tagline:          'Jose Simoes Home Page'
description:      'Currently CPO @ <a href="http://dafiti.com.br" target="_blank">Dafiti</a> Entrepreneur, bitcoin enthusiast and recently investor. Find more about me at <a href="https://twitter.com/jmsimoes" target="_blank">@jmsimoes</a>'
url:              http://www.josesimoes.com
baseurl:          /

author:
  name:           'Jose Simoes'
  url:            https://twitter.com/jmsimoes

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jsimoes/jsimoes.github.io
  
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-30911564-1
